### ISSUE TITLE
As a user, I want to see 'Total SKS' on my saved schedule

### ISSUE THREAD

**Issue by indravb6** [ristekoss/susunjadwal#30]
**This issue is a:** 

- [ ] bug report
- [x] feature request
- [ ] styling change request

**Current behavior:**

Can't see 'Total SKS' on my saved schedule

**Requested behavior:**

Can see 'Total SKS' on my saved schedule

**Why this behavior is better:**

**Comment by satraul** [comment]
Agreed. An additional field for SKS needs to be added to the `user_schedule` model.
