### ISSUE TITLE
Rebrand Edit Jadwal Color Scheme

### ISSUE THREAD

**Issue by jonathanfilbert** [ristekoss/susunjadwal#95]
**This issue is a:** 

- [ ] bug report
- [ ] feature request
- [x] styling change request

**Current behavior:**
The current edit jadwal page still incorporates the old color schemes (black and orange).

**Requested behavior:**
Change the color into white and purple 

**Why this behavior is better:**
UI consistency.

**Comment by fahdikrie** [comment]
Actually, I already done revamping edit jadwal page on #94 too :D

**Comment by jonathanfilbert** [comment]
Awesome 👍
